### ISSUE TITLE
Account management tools to allow changes to Lockbox preferences without interfering with password management actions

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-extension#384]
When I want to manage my Lockbox account, such as sign out or edit my preferences, I want to easily do that from my editor without interfering with my other password management activities.

https://mozilla.invisionapp.com/share/CTEFRXMZ7#/264252691_1-1-0_Lockbox_Home_-_Authenticated_Profile_Doorhanger

![Screenshot-2018-1-2 LockBox (Fx Add-On) Preview Mode - InVision.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dc07ab1a9a2600115c9b6f/125516c66e82c728ace21e0d46db978826878dba87e6ab0ef60da1cc64176a216928ac287ba7ec30ff0a5d194f2e1af85c27015dec99cb7ee0ef69379a2154b9847d4264bf6377f5fbdb40e113a632cb0ddaece9d908d2e22f20eedf8b1b361d061cdaab0b32a2994bca5df31fb21b04f2012a71a427682818c9473f7929752cb9fdd85c868061a0b3102e54cde7e3f31500ec.png)

## Acceptance criteria
- Should be able to access additional account management tools without interference with primary password management activities.

## Expected behavior
- provide multiple account options under a drop down menu, starting with the following items:
   * "Account" - links to FxA account settings: https://accounts.firefox.com/settings
   * "Sign out" - #149
   * "Preferences" - addons options
- if account is secured by FxA, display avatar as provided by FxA
- if avatar is not available, display email address
- if account is not secured by FxA, display default image (needs design)
- if account is not secured by FxA, drop down menu only displays "preferences"
- manage account properties only from the full editor with no mini-editor option to access these settings (to revisit)

## Relevant user stories
- [x] #417 (display avatar and profile name from FxA)
- [x] #442 (display dropdown menu and links)
- [x] #149 (Allow user to "Lock" editor via "Sign Out")

## Related
* Epic #209 "Lock your Lockbox"

_Follow up from PR #362_

**Comment by changecourse** [comment]
It is worth noting, I have some concerns about the potential for user confusion between "Account" and "Preferences." I'm curious if we need to have a way for someone to access their extension preferences via our editor view, rather than just the current way in which this is usually accessed, via the Add-ons Manager list... Thoughts @linuxwolf, @jimporter, @hmcgaw, or @sandysage? 

Then I'd update the design to only have "Account" for FxA access (+ Sign Out)
