### ISSUE TITLE
Photon updates, 3rd pass

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#392]
Continuing the work started at #331 and #351

Zeplin: https://app.zeplin.io/project/59fb4868c5e7608593f76965

## Todo

- [x] zero entries / first run home page with 3-up feature heros #292 
- [x] review all copy text once more..
------
- [x] "Disabled"/inactivate/muted state of the sidebar list items when an item is selected (greys out all entries but the one selected)
- [x] Disabled "Home" button when not on a item detail (create, edit, view) view (aka can't click "Home" when home)
- [x] Disable "Save Entry" until at least one field has been populated
---
- [x] `<ItemDetails/>` (and `<EditItemDetails/>`) are designed as (theoretically) reusable components that could be put anywhere. Somewhere in `<CurrentSelection/>` would be a better place
  - [x] Content area bg for the selected item should match either of these two values depending
------
- [x] doorhanger search padding to have more space
- [x] "manage lockbox" button shorter, background color? (instead of ghost button, make it a puffy?)
- [x] entry details: move "title" to title bar (out of detail view) and shorter
- [x] extend background of item details all the way to bottom of screen (content area is gray, white space beneath)
- [x] red alert button style for delete (keep primary for discard)
- [x] Search bar magnify icon ~and clear icon (when populated)~ based on screenshot below: <img width="260" alt="screen shot 2017-11-13 at 11 41 21 am" src="https://user-images.githubusercontent.com/6164801/32742816-b9918336-c867-11e7-995a-8de86e47d694.png">
- [x] a little wider width for doorhanger?
- [x] sidebar: secondary (no username)" and "(no site name)" CSS treatment (lighter color)
-----
* [x] Reordering the item fields (not sure if we need to do anything about this, though I do have a feeling we'll end up reverting this when we have multi-origin support)
* [x] Bold-face or not on the non-editable item fields (just something for @changecourse to think about; see above)
* [x] Miscellaneous small issues with the item list

**Comment by devinreams** [comment]
Added more leftover items from #351 above. This is our "post launch" discussion/todo/to-decide list and currently at the top of the backlog due to the fact a) some of the attempted work is in-complete and b) the accumulation of tech debt started in that branch.

**Comment by changecourse** [comment]
Closing this issue, as we'll be breaking up new design needs on a 'per-component' basis rather than grouped in such a large manner moving forward, per a discussion with @sandysage 

New issues (by component) forthcoming, and will include some of the tasks listed above in a more organized manner...
