### ISSUE TITLE
IA Updates: Header Bar & Creating an Entry

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#444]
Improving the relationship between the "Create Entry" button and the entry list, based on past usability concerns (from Alpha) and feedback from the team during all-hands. 

(EDIT: cleaned up past conversation and feedback on outdated designs)

## Visual Design

**InVision**
https://mozilla.invisionapp.com/share/CTEFRXMZ7#/262163357_1-1-1_Lockbox_Home_-_View_Entry

**Zeplin**
https://zpl.io/begk4BD

**Tasks (may need to be broken up into separate issues)**
- [x] Removal of the home button
- [x] Navigating to home will now be accomplished via breadcrumb navigation, only available when at least one level deep (such as within the entry detail, see designs) Breadcrumbs should not be displayed at the root level (Home)
- [x] Revision of the 'entry button' to match the revised designs (now as a '+' alongside the search)
- [x] Removal of the header background bar (sidebar is now flush with the top, account and FAQ links float in the Home content area
- [x] Move the feedback link to the base of the entries sidebar, as a fixed callout

**Comment by changecourse** [comment]
@hmcgaw I've come up with some potential options for adjusting our IA to better incorporate the action (Create New Entry) to the Entries List itself... Ready for review and proposal for testing via usertesting, per our conversation before the holidays. 

I've ordered these based on my perception of the 'right' way for alignment between action and list. 

![0 current](https://user-images.githubusercontent.com/6164801/34582708-2880d234-f152-11e7-9396-cbacdab5ee99.png)
![1 doorhanger parity](https://user-images.githubusercontent.com/6164801/34582709-289ceb7c-f152-11e7-95ef-1a3fc2d1e458.png)
![3 inline add to list](https://user-images.githubusercontent.com/6164801/34582710-28b1d69a-f152-11e7-86ec-063c61662719.png)
![4 global action add](https://user-images.githubusercontent.com/6164801/34582711-28c95158-f152-11e7-9d5b-f21f924ef759.png)
![5 floating new entry](https://user-images.githubusercontent.com/6164801/34582712-28dde8a2-f152-11e7-96b1-99e5c7c8fbb0.png)

**Comment by pdehaan** [comment]
I like the **"Doorhanger Parity"** option. Keeps it in a consistent location. The **"Inline Adding to List"** is also nice and consistent, but I feel like it blends into the list too easily.

I'm not sure how well **"Global Action for Adding"** or **"Floating New Entry"** would behave once we many items and vertical scrolling.

In fact, I think that'd be my preferred option order (not that this was a poll or anything):
1. Doorhanger Parity
2. Inline Adding to List
3. Global Action for Adding
4. Floating New Entry

**Comment by jimporter** [comment]
@changecourse Everything but the current implementation has the issue that the "home" button is gone. This means that there'd be no way to get back to the homepage (unless you reload the page) if you wanted to sign up (or sign in) with FxA.

**Comment by changecourse** [comment]
@jimporter Understood. I think the plan (pending our direction for the sidebar approach) would be to change how the entry details is shown, potentially animating in as a drawer that can be opened and closed, and also having the ability to 'close' out of an active entry detail, thus allowing the user to easily return to the 'home' state.

**Comment by hmcgaw** [comment]
It's not clear from the comps what the change in IA is, for example it's unclear whether the entry slides out over top of the home screen or whether it's a new page. If it's the latter it would be worth considering the placement and behaviour or the FAQ and Feedback links.

Assuming the the behaviour of the entry when being opened (for new and existing) could be the same for all of the versions, is there a design for that? 

In terms of the design variations, Inline Adding to List and Doorhanger parity both seem promising in that that button is available in the context of where the users' attention would be given. 

What are the next steps here? Were you hoping to run a study on one or two of these designs?

**Comment by changecourse** [comment]
> It's not clear from the comps what the change in IA is, for example it's unclear whether the entry slides out over top of the home screen or whether it's a new page. If it's the latter it would be worth considering the placement and behaviour or the FAQ and Feedback links.

This is something I've been thinking about... do we have a strong case to be made for FAQ and Feedback links always needing to be available and clickable to users, or can we consider their presence within the home state as satisfactory? 

> Assuming the the behaviour of the entry when being opened (for new and existing) could be the same for all of the versions, is there a design for that?

Not as of yet, though in progress... the new design approach for adding would necessitate a detail page that behaves differently (animation from point of origin, clicking on the list) as well as functionality (needing a close button or equivalent within the detail container) Also worth considering whether or not the detail page is layered over the home screen, with clickable areas to dismiss details in a secondary manner

> What are the next steps here? Were you hoping to run a study on one or two of these designs?

Ideally yes, we could decide on 1-2 approaches and either test against our current design or independent of it.

**Comment by hmcgaw** [comment]
Okay. Once the work you're doing on this userflow is in a shareable state we can talk about options for evaluation and get rolling with that. 

For that conversation I'll need a user flow to understand the interactions and IA, but it doesn't need to be a set of comps - annotated wireframes/user flow would be sufficient. :)

**Comment by changecourse** [comment]
Moving back to "To-Do" 

Will need to reassess size based on effort around a more comprehensive user flow and screens for adding an entry...

**Comment by sandysage** [comment]
Moving back to backlog for prioritization.

**Comment by changecourse** [comment]
New designs ready for implementation, specifically the revisions to the nav bar and inclusion of breadcrumbs to replace the home button.

**Comment by changecourse** [comment]
Updated this ticket to address the latest design revisions and break out into tasks, both functional and visual... Nick can work on PR's associated with the visual tasks.

**Comment by changecourse** [comment]
@devinreams let me know if you'd like me to break out some of these tasks into individual issues, such as the breadcrumb nav (vs. Home as it currently functions) based on LOE.

**Comment by changecourse** [comment]
Moving out of "Good first issue" for now, due to the depth of changes listed in the tasks above.

Let's discuss during our next sprint planning session on how we'd like to break up the associated changes requested for the Nav and primary action.

**Comment by jimporter** [comment]
@changecourse In the spec, I notice that the search bar and the breadcrumb area are different heights. I just wanted to see if this was intentional; I think we'd be able to make them the same height, which might look better, but we'd have to change the padding on the breadcrumb area (especially the user's avatar, which is the tallest element in the spec).

**Comment by changecourse** [comment]
Yeah, this was intentional, specifically because of the height of the avatar, which would be pretty tight to the top of the window if we tried to align all three elements (search, breadcrumbs, and account)

I tried it both ways and elected to have the content area to have a top bar lockup independent of the sidebar lockup. 

<img width="1211" alt="screen shot 2018-03-12 at 1 00 39 pm" src="https://user-images.githubusercontent.com/6164801/37303934-b268173c-25f5-11e8-962f-ecd4754befe1.png">

**Comment by changecourse** [comment]
@jimporter I think this issue would be a good opportunity for joint collaboration on a branch, where you can do the functional work of removal, breadcrumbing, and where these elements should live within the architecture of the app, then hand it off to @nickbrandt for styling of the revised New Entry button, styling of the breadcrumbs, and position of the elements on the page.
