### ISSUE TITLE
Create/Edit Entry Fields update

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#457]
## Designs
https://mozilla.invisionapp.com/share/W3EU997YN#/263643956_1-1-0_Lockbox_Home_-_New_Entry_-_Unfilled 
https://mozilla.invisionapp.com/share/W3EU997YN#/262163359_1-1-2_Lockbox_Home_-_Edit_Entry

## ToDo

- [ ] Form field vertical padding between fields in both the read-only and edit mode (20px)
- [ ] Button widths (132px for primary, 80px for secondary)
- [ ] Margins for fields within content window (40/40 from left and top)
- [ ] Disable "Save Entry" until at least one field has been populated
<ItemDetails/> (and <EditItemDetails/>) are designed as (theoretically) reusable components that could be put anywhere. Somewhere in <CurrentSelection/> would be a better place (Pulled over from Photon updates from Devin, needs explanation)
- [ ] Padding/placement of Discard Changes & Delete dialog to match comps
- [ ] Red delete button
