### ISSUE TITLE
Populate saved credentials efficiently from the doorhanger to keep the user in context of the login

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#467]
When I want to log into an account with credentials I already have saved, I want to conveniently fill those in the web form so I can log in quickly.

## Acceptance criteria
1. Should have control over what gets populated
2. Should be able to fill a web form in 3 clicks or less (reduces the current overhead of min of 5 clicks)
3. Should have a clear backup option for copy/paste for when fill doesn't work

User stories for:
- [ ] interaction design to enable user involvement (user control over what gets populated and where which won't happen automatically to start)
- [ ] collection of websites that we want to target to make sure it works 
- [ ] port behind-the-scenes logic from Firefox for form detection
- [ ] wire it up in a way we can use it to fill usernames/passwords

NOTE: This is the follow up to issue #241 progressing from making it easier to copy from the doorhanger to porting the existing login manager login into a Web Extension

**Comment by sandysage** [comment]
This is the building block on top of #341 which uses the URI to provide more relevant results. Based on those more filtered results we can provide better tools for populating the login.
