### ISSUE TITLE
DR: Refine the items/entries list to better align to photon & more be informative for new users

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#475]
Updates to the entries list in the editor view. 

**Design Prototype: https://mozilla.invisionapp.com/share/W3EU997YN#/263643956_1-1-0_Lockbox_Home_-_New_Entry_-_Unfilled**

**Zeplin (requires account): https://zpl.io/an6g71l**

## Tasks ##
- [x] Revised styling of entry list background active state and focus state
- [x] Change uppercase “Entry’ to ‘entry’ in help text on sidebar
- [x] Increase vertical size of list item to 72px
- [ ] Do not display blue focus state until prompted by keyboard control
- [ ] Replace (no username) label with instructions copy (enter your login details)
- [x] Use provided right-chevron for entry in list (attached)
[chevron-right.svg.zip](https://github.com/mozilla-lockbox/lockbox-extension/files/1652753/chevron-right.svg.zip)
