### ISSUE TITLE
DR: Refine the welcome screen to have more visual readability

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#476]
*Updates to the welcome screen, first time use of Lockbox*

**Inivision: https://mozilla.invisionapp.com/share/W3EU997YN#/264173555_1-0-0_Lockbox_Home_-_Welcome_Screen**

**Zeplin: https://zpl.io/an6g71l**

## Tasks ##
- [ ] Update padding to spec (between CTAs and intro section)
- [ ] Change copy of secondary button to “Sign in”
- [ ] Change subheader for returning users to “Have an account?”
- [ ] Order buttons/subheaders to be inline instead of stacked

**Comment by nickbrandt** [comment]
Merged these tasks with #481
