### ISSUE TITLE
DR: Update the search bar to align to photon & make it easier to understand and get to relevant results fast

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#477]
*Updates to the search bar in the entry sidebar*

**Invision: https://mozilla.invisionapp.com/share/W3EU997YN#/264245494_1-1-0_Lockbox_Home_-_0_Entries**

**Zeplin: https://zpl.io/an6g71l**

## Tasks ##
- [x] Custom styling (different than Photon) padding/size of input
- [x] Search Icon inclusion
- [x] Replace text link for clearing field with 'clear icon'
- [x] Removal of the term ‘entries’ and use "Search Lockbox"
- [x] Clear icon for text input (instead of text label)

**Comment by jimporter** [comment]
@changecourse Do we have SVG assets for the search/clear icons anywhere?

**Comment by changecourse** [comment]
@jimporter sure thing! 

[icons.zip](https://github.com/mozilla-lockbox/lockbox-extension/files/1679162/icons.zip)
