### ISSUE TITLE
DR: Refine the ‘create’ and ‘edit’ entry forms to better align to photon

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#479]
*Adjustments to the form fields of 'Create Entry' and 'Edit Entry'*

**Invision (Create): https://mozilla.invisionapp.com/share/W3EU997YN#/263643956_1-1-0_Lockbox_Home_-_New_Entry_-_Unfilled**

**Invision (Edit): https://mozilla.invisionapp.com/share/W3EU997YN#/262163359_1-1-2_Lockbox_Home_-_Edit_Entry**

**Zeplin: https://zpl.io/an6g71l**

## Tasks ##
- [x] Form field vertical padding between fields in both the read-only and edit mode (20px)
Button widths (132px for primary, 80px for secondary)
- [x] Change ‘site address’ to ‘website address’ throughout
- [x] Margins for fields within content window (40/40 from left and top)
- [x] Padding/placement of Discard Changes & Delete dialog to match comps
- [x] Red delete button
