### ISSUE TITLE
DR: Refine the entry details to be better aligned to photon

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#480]
*The read-only, entry details view of the editor*

**Inivision: https://mozilla.invisionapp.com/share/W3EU997YN#/270503568_1-1-1_Lockbox_Home_-_Focus_Change**

**Zeplin: https://zpl.io/an6g71l**

## Tasks ##
- [x] Vertical padding between fields to match the create/edit inputs seamlessly
- [x] ~~Vertical padding between header and content~~ -Included with #479 
- [x] Styling of password dots in read-only state (Fira Monospace)
- [x] ~~Update input background to #ffffff~~ -Included with #479

**Comment by jimporter** [comment]
@changecourse What's Shadow 30? I don't see it in the Photon spec...

**Comment by changecourse** [comment]
https://design.firefox.com/photon/patterns/shadows.html
