### ISSUE TITLE
DR: Doorhanger entries list, align to photon

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#483]
*Many of the changes requested in this story may be inhereted by default from the changes requested to the entries list of the editor view*

**Invision: https://mozilla.invisionapp.com/share/W3EU997YN#/262323598_D_1-1-0_Default_-_Entries_List**

## Tasks ##
- [x] Expand padding of search box within doorhanger
- [x] ~~Change placeholder content to remove “Entries”~~ -included with #562 
- [x] ~~Styling of doorhanger footer “Manage Lockbox” to match designs (full row clickable)~~ included with #601 
- [x] Decide on max/min-width for default doorhanger experience (what is implemented is narrower than what was posed in designs) 320px is posed --Updated to 320 to match sign-in DH
- [x] Inherit the updates to entry cards from full-tab revisions (height, chevron, etc)
- [x] Focus state of an entry within the doorhanger list (I couldn’t activate it via keyboard)

**Comment by devinreams** [comment]
@nickbrandt Sorry but I got confused looking at this issue.

It's marked as "in progress" but I didn't see corresponding PR(s) to go with it. And I see the tasks checked off. Is this up to date?

**Comment by nickbrandt** [comment]
@devinreams that's correct, #619 is the PR that goes with this work. There are a couple items in there that we have discussed with @jimporter yesterday and will be adjusting. There are a few things he wanted to get a closer look on before making the final call.
