### ISSUE TITLE
Provision test and production Kinto instances

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-extension#489]
In service to sync, test and production instances of Kinto need to be made available.

## Tasks
- [ ] work with ops to determine deployment plan
- [ ] record test instance configuration information (e.g., service domain name)
- [ ] record production instance configuration information (e.g., service domain name)

**Comment by linuxwolf** [comment]
-stage environment (dev/test): https://bugzilla.mozilla.org/show_bug.cgi?id=1436556

**Comment by m8ttyB** [comment]
Does this need-pi?

**Comment by linuxwolf** [comment]
@m8ttyB no it does not.

**Comment by linuxwolf** [comment]
Staging deployed:
* URL ==  https://kinto-lockbox.stage.mozaws.net/v1/

**Comment by sandysage** [comment]
Need to verify this is set up and works for what we need.
