### ISSUE TITLE
Integrate Datastore sync implementation to allow users to retrieve and store their entries in the cloud

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-extension#492]
In service to sync, integrate the core sync process from the [datastore](/mozilla-lockbox/lockbox-datastore) into the extension.

## Todo

- [ ] make appropriate calls on DataStore instance to trigger a sync.
  * on `sync` message (manual trigger hook)
  * on `upgrade_account` message
  * on `add_item` / `update_item` / `remove_item` messages
  * on a timer
- [ ] report any sync errors to logs.
- [ ] record telemetry when the sync operation completes.

## Related
* mozilla-lockbox/lockbox-datastore#50
