### ISSUE TITLE
iOS Research, Round 1

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#629]
This is the proposed set of tasks for iOS research, to be broken out into separate stories as needed:

**Tasks**
- [ ] Research kickoff (questions, goals)
- [ ] Prepare research protocol
- [ ] Build study (if unmoderated) OR begin recruitment (if moderated)
- [ ] Observe sessions OR conduct study
- [ ] Analyze data
- [ ] Prepare findings for distribution

**Decisions to be made**
- [ ] Usability focus OR context and behaviors
- [ ] iOS in isolation OR paired with the web extension
- [ ] Invision clickthrough OR working applications
- [ ] Unmoderated OR Moderated approach
